version: '3'

services:
    app:
        build:
            context: .
        ports:
            - "8000:8000"
        volumes:
            - ./app:/app
            - ./drugs.json:/drugs.json
        command: >
            sh -c "python manage.py wait_for_db &&
                python manage.py migrate &&
                python manage.py load_data /drugs.json &&
                python manage.py runserver 0.0.0.0:8000"
        environment:
            - DB_HOST=drugs_db
            - DB_NAME=app
            - DB_USER=postgres
            - DB_PASS=supersecret
        depends_on:
            - drugs_db

    drugs_db:
        image: postgres:10-alpine
        environment:
            - POSTGRES_DB=app
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=supersecret 