# Generated by Django 3.1.13 on 2021-07-18 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Generic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MOA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moa', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=255)),
                ('product_ndc', models.CharField(max_length=13)),
                ('start_date', models.CharField(max_length=8)),
                ('end_date', models.CharField(max_length=8)),
                ('brand_name', models.CharField(max_length=255)),
                ('dea_schedule', models.CharField(max_length=10, null=True)),
                ('generic_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.generic')),
                ('moa', models.ManyToManyField(to='core.MOA')),
                ('routes', models.ManyToManyField(to='core.Route')),
            ],
        ),
    ]
