# Generated by Django 3.0.8 on 2020-07-21 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='drug',
            name='routes',
            field=models.ManyToManyField(to='core.Route'),
        ),
    ]
