# Generated by Django 3.0.8 on 2020-07-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200721_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='product_id',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
