# Generated by Django 3.0.8 on 2020-07-22 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_moa'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='moa',
            field=models.ManyToManyField(to='core.MOA'),
        ),
    ]
