# Generated by Django 3.0.8 on 2020-07-23 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_drug_moa'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='dea_schedule',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
