# Generated by Django 3.0.8 on 2020-07-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_drug_dea_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='dea_schedule',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
